apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiconversao
spec: 
  selector:
    matchLabels:
      app: apiconversao
  template:
      metadata: 
        labels:
          app: apiconversao
      spec:
        containers:
          - name: apiconversao
            image: nelsondanielbusiness/api-conversao:1
            ports:
              - containerPort: 8080